name: Build Komprimieren

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Build Executable
        run: |
          cd Komprimieren
          dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: komprimieren-executable
          path: Komprimieren/bin/Release/net9.0/win-x64/publish/Komprimieren.exe
