name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true
        default: '1.0.0'

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build_komprimieren.yml
          ref: main # Passe den Branch an, falls nötig
          inputs: |
            version=${{ github.event.inputs.version }}

  release:
    needs: trigger-build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: komprimieren-executable

      - name: Create Git Tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a v${{ github.event.inputs.version }} -m "Release version ${{ github.event.inputs.version }}"
          git push origin v${{ github.event.inputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          files: |
            Komprimieren.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
