name: Create Release and Build Executable

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Extract Version from meta.yaml
        id: get_version
        run: |
          VERSION=$(grep 'version:' meta.yaml | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted Version: $VERSION"

      - name: Create Git Tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a v${{ steps.get_version.outputs.version }} -m "Release version ${{ steps.get_version.outputs.version }}"
          git push origin v${{ steps.get_version.outputs.version }}

      - name: Build Executable
        run: |
          cd Komprimieren
          dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true
          cd bin/Release/net8.0/win-x64/publish

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          files: |
            Komprimieren/bin/Release/net8.0/win-x64/publish/Komprimieren.exe

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
